language: node_js

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - "if [ $LINT ]; then npm run lint; fi"
  - "if [ $COVERAGE ]; then npm run cover && bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info; fi"
  - "if [ $RUN_TEST ]; then npm run test; fi"

jobs:
  include:
    - stage: tests
      node_js: 6
      env: RUN_TEST=true
    - stage: tests
      node_js: 7
      env: RUN_TEST=true
    - stage: tests
      node_js: 8
      env: RUN_TEST=true
    - stage: tests
      node_js: node
      env: RUN_TEST=true
    - stage: coverage
      node_js: 6
      env: COVERAGE=true
    - stage: lint
      node_js: 6
      env: LINT=true